#spring.application.name=SpringSecurity
#spring.data.mongodb.host=localhost
#spring.data.mongodb.port=27017
#spring.data.mongodb.database=securityDb
#server.servlet.context-path=/secur

anthropic.api-key=${ANTHROPIC_API_KEY:}
